# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 14:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressOfDrugstore',
            fields=[
                ('block_number', models.CharField(max_length=5)),
                ('alley', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('tel', models.IntegerField()),
                ('postal_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('Commercial_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Generic_name', models.CharField(max_length=20)),
                ('Dose', models.IntegerField()),
                ('Side_effects', models.CharField(max_length=100)),
                ('How_to_use', models.CharField(max_length=100)),
                ('Drug_interactions', models.CharField(max_length=100)),
                ('Compositions', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Necessity_of_prescription', models.IntegerField()),
                ('Drug_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address_list', models.ManyToManyField(to='drugstoreapp.AddressOfDrugstore')),
                ('drug_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugstoreapp.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('drug_store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugstoreapp.DrugStore')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugstoreapp.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugstoreapp.Drug')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='patiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugstoreapp.Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ManyToManyField(to='drugstoreapp.OrderModel'),
        ),
        migrations.AddField(
            model_name='drugstore',
            name='storage_list',
            field=models.ManyToManyField(to='drugstoreapp.StorageModel'),
        ),
    ]
