# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstore',
            name='id',
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
