# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugstoreapp', '0002_auto_20171208_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patiant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
    ]
